export {
  Card,
  CardImgContainer,
  CardTitle,
  CardPrice,
  CardPriceRegular,
  CardPriceDiscount,
  Line,
  CardProperties,
  CardSpec,
  CardSpecValue,
  Buttons,
  ButtonAdd,
  ButtonAdded,
  ButtonFavorite,
} from './ProductCard.styled';
